export const cdnBase = "https://nicola-gasparri.b-cdn.net";

export const projects_nicola = [
  {
    artist: "nicola",
    id: "apple-security",
    video: "/project-videos/apple-security.mp4",
    name: "Apple Security",
    director: "Adam Liu",
    cinematographer: "TianXing Wang",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/apple-security/apple-security-coverImg.png",
    span: 4,
    images: [
      "/nicola/apple-security/1.jpg",
      "/nicola/apple-security/2.jpg",
      "/nicola/apple-security/3.jpg",
      "/nicola/apple-security/4.jpg",
      "/nicola/apple-security/5.jpg",
      "/nicola/apple-security/6.jpg",
      "/nicola/apple-security/7.jpg",
      "/nicola/apple-security/8.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "neeraj",
    video: "/project-videos/samsung.mp4",
    name: "Neeraj",
    director: "Aakash Bhatia",
    cinematographer: "Konrad Losch",
    productionCompany: "Loudmouth",
    category: "TVC",
    cover: "/nicola/neeraj/neeraj-coverImg.JPG",
    span: 2,
    images: [
      "/nicola/neeraj/1.JPG",
      "/nicola/neeraj/2.jpg",
      "/nicola/neeraj/3.jpg",
      "/nicola/neeraj/4.jpg",
      "/nicola/neeraj/5.jpg",
      "/nicola/neeraj/6.jpg",
      "/nicola/neeraj/7.jpg",
      "/nicola/neeraj/8.jpg",
      "/nicola/neeraj/9.jpg",
      "/nicola/neeraj/10.jpg",
      "/nicola/neeraj/11.jpg",
      "/nicola/neeraj/12.jpg",
      "/nicola/neeraj/13.jpg",
      "/nicola/neeraj/14.jpg",
      "/nicola/neeraj/15.jpg",
      "/nicola/neeraj/16.jpg",
      "/nicola/neeraj/17.jpg",
      "/nicola/neeraj/18.jpg",
      "/nicola/neeraj/19.jpg",
      "/nicola/neeraj/20.jpg",
      "/nicola/neeraj/21.JPG",
      "/nicola/neeraj/22.JPG",
    ],
  },
  {
    artist: "nicola",
    id: "astropulse",
    video: "/project-videos/astropulse.mp4",
    name: "Astropulse",
    director: "Wei Wang",
    cinematographer: "",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/astropulse/astropulse-coverImg.jpg",
    span: 2,
    images: [
      "/nicola/astropulse/1.jpg",
      "/nicola/astropulse/2.jpg",
      "/nicola/astropulse/3.jpg",
      "/nicola/astropulse/4.jpg",
      "/nicola/astropulse/5.jpg",
      "/nicola/astropulse/6.jpg",
      "/nicola/astropulse/7.jpg",
      "/nicola/astropulse/8.jpg",
      "/nicola/astropulse/9.jpg",
      "/nicola/astropulse/10.jpg",
      "/nicola/astropulse/11.jpg",
      "/nicola/astropulse/12.jpg",
      "/nicola/astropulse/13.jpg",
      "/nicola/astropulse/14.jpg",
      "/nicola/astropulse/15.jpg",
      "/nicola/astropulse/16.jpg",
      "/nicola/astropulse/17.jpg",
      "/nicola/astropulse/18.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "lotus-limitless",
    video: "/project-videos/lotus-limitless.mp4",
    name: "Lotus Limitless",
    director: "Yao Fei",
    cinematographer: "Lu Xiqi",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/lotus-limitless/lotus-limitless-coverImg1.jpg",
    span: 4,
    images: [
      "/nicola/lotus-limitless/1.jpg",
      "/nicola/lotus-limitless/2.jpg",
      "/nicola/lotus-limitless/3.jpg",
      "/nicola/lotus-limitless/4.jpg",
      "/nicola/lotus-limitless/5.jpg",
      "/nicola/lotus-limitless/6.jpg",
      "/nicola/lotus-limitless/7.jpg",
      "/nicola/lotus-limitless/8.jpg",
      "/nicola/lotus-limitless/9.jpg",
      // "/nicola/lotus-limitless/10.jpg",
      "/nicola/lotus-limitless/11.jpg",
      "/nicola/lotus-limitless/12.jpg",
      "/nicola/lotus-limitless/13.jpg",
      "/nicola/lotus-limitless/14.jpg",
      "/nicola/lotus-limitless/15.jpg",
      "/nicola/lotus-limitless/16.jpg",
      "/nicola/lotus-limitless/17.jpg",
      "/nicola/lotus-limitless/18.jpg",
      "/nicola/lotus-limitless/19.jpg",
      "/nicola/lotus-limitless/20.jpg",
      "/nicola/lotus-limitless/21.jpg",
      "/nicola/lotus-limitless/22.jpg",
      "/nicola/lotus-limitless/23.jpg",
      "/nicola/lotus-limitless/24.jpg",
      "/nicola/lotus-limitless/25.jpg",
      "/nicola/lotus-limitless/26.jpg",
      "/nicola/lotus-limitless/27.jpg",
      "/nicola/lotus-limitless/28.jpg",
      "/nicola/lotus-limitless/29.jpg",
      "/nicola/lotus-limitless/30.jpg",
      "/nicola/lotus-limitless/31.jpg",
      "/nicola/lotus-limitless/32.jpg",
      "/nicola/lotus-limitless/33.jpg",
      "/nicola/lotus-limitless/34.jpg",
      "/nicola/lotus-limitless/35.jpg",
      // "/nicola/lotus-limitless/36.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "honkai-star-trail",
    video: "/project-videos/honkai-star-trail.mp4",
    name: "Honkai Star Trail",
    director: "Omer Ben Shachar",
    cinematographer: "Kai Krause",
    productionCompany: "",
    category: "Film",
    cover: "/nicola/honkai-star-trail/honkai-star-trail-coverImg2.jpg",
    span: 4,
    images: [
      "/nicola/honkai-star-trail/1.jpg",
      "/nicola/honkai-star-trail/2.jpg",
      "/nicola/honkai-star-trail/3.jpg",
      "/nicola/honkai-star-trail/4.jpg",
      "/nicola/honkai-star-trail/5.jpg",
      "/nicola/honkai-star-trail/6.jpg",
      "/nicola/honkai-star-trail/7.jpg",
      "/nicola/honkai-star-trail/8.jpg",
      "/nicola/honkai-star-trail/9.jpg",
      "/nicola/honkai-star-trail/10.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "blossom-shanghai",
    video: "/project-videos/blossom-shanghai.mp4",
    name: "Blossom Shanghai",
    director: "Wong Kar-wai",
    cinematographer: "Peter Pau",
    productionCompany: "",
    category: "Film",
    cover: "/nicola/blossom-shanghai/blossom-shanghai-coverImg1.jpg",
    span: 2,
    images: [
      "/nicola/blossom-shanghai/1.jpg",
      "/nicola/blossom-shanghai/2.jpg",
      "/nicola/blossom-shanghai/3.jpg",
      "/nicola/blossom-shanghai/4.jpg",
      "/nicola/blossom-shanghai/5.jpg",
      "/nicola/blossom-shanghai/6.jpg",
      "/nicola/blossom-shanghai/7.jpg",
      "/nicola/blossom-shanghai/8.jpg",
      "/nicola/blossom-shanghai/9.jpg",
      "/nicola/blossom-shanghai/10.jpg",
      "/nicola/blossom-shanghai/11.jpg",
      "/nicola/blossom-shanghai/12.jpg",
      "/nicola/blossom-shanghai/13.jpg",
      "/nicola/blossom-shanghai/14.jpg",
      "/nicola/blossom-shanghai/15.jpg",
      "/nicola/blossom-shanghai/16.jpg",
      "/nicola/blossom-shanghai/17.jpg",
      "/nicola/blossom-shanghai/18.jpg",
      "/nicola/blossom-shanghai/19.jpg",
      "/nicola/blossom-shanghai/20.jpg",
      "/nicola/blossom-shanghai/21.jpg",
      "/nicola/blossom-shanghai/22.jpg",
      "/nicola/blossom-shanghai/23.jpg",
      "/nicola/blossom-shanghai/24.jpg",
      "/nicola/blossom-shanghai/25.jpg",
      "/nicola/blossom-shanghai/26.jpg",
      "/nicola/blossom-shanghai/27.jpg",
      "/nicola/blossom-shanghai/28.jpg",
      "/nicola/blossom-shanghai/29.jpg",
      "/nicola/blossom-shanghai/30.jpg",
      "/nicola/blossom-shanghai/31.jpg",
      "/nicola/blossom-shanghai/32.jpg",
      "/nicola/blossom-shanghai/33.jpg",
      "/nicola/blossom-shanghai/34.jpg",
      "/nicola/blossom-shanghai/35.jpg",
      "/nicola/blossom-shanghai/36.jpg",
      "/nicola/blossom-shanghai/37.jpg",
      "/nicola/blossom-shanghai/38.jpg",
      "/nicola/blossom-shanghai/39.jpg",
      "/nicola/blossom-shanghai/40.jpg",
      "/nicola/blossom-shanghai/41.jpg",
      "/nicola/blossom-shanghai/42.jpg",
      "/nicola/blossom-shanghai/43.jpg",
      "/nicola/blossom-shanghai/44.jpg",
      "/nicola/blossom-shanghai/45.jpg",
      "/nicola/blossom-shanghai/46.jpg",
      "/nicola/blossom-shanghai/47.jpg",
      "/nicola/blossom-shanghai/48.jpg",
      "/nicola/blossom-shanghai/49.jpg",
      "/nicola/blossom-shanghai/50.jpg",
      "/nicola/blossom-shanghai/51.jpg",
      "/nicola/blossom-shanghai/52.jpg",
      "/nicola/blossom-shanghai/53.jpg",
      "/nicola/blossom-shanghai/54.jpg",
      "/nicola/blossom-shanghai/55.jpg",
      "/nicola/blossom-shanghai/56.jpg",
      "/nicola/blossom-shanghai/57.jpg",
      "/nicola/blossom-shanghai/58.jpg",
      "/nicola/blossom-shanghai/59.jpg",
      "/nicola/blossom-shanghai/60.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "beats",
    video: "/project-videos/beats.mp4",
    name: "Beats",
    director: "Zika Liu",
    cinematographer: "Liu Chao",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/beats/beats-coverImg.jpg",
    span: 2,
    images: [
      "/nicola/beats/1.jpg",
      "/nicola/beats/2.jpg",
      "/nicola/beats/3.jpg",
      "/nicola/beats/4.jpg",
      "/nicola/beats/5.jpg",
      "/nicola/beats/6.jpg",
      "/nicola/beats/7.jpg",
      "/nicola/beats/8.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "royal-enfield",
    video: "/project-videos/royal-enfield.mp4",
    name: "Royal Enfield",
    director: "Aakash Bhatia",
    cinematographer: "Vikash Nowlakha",
    productionCompany: "Loudmouth",
    category: "TVC",
    cover: "/nicola/royal-enfield/royal-enfield-coverImg.jpg",
    span: 4,
    images: [
      "/nicola/royal-enfield/1.jpg",
      "/nicola/royal-enfield/2.jpg",
      "/nicola/royal-enfield/3.jpg",
      "/nicola/royal-enfield/4.jpg",
      "/nicola/royal-enfield/5.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "bmw-x5",
    video: "/project-videos/bmw-x5.mov",
    name: "Bmw X5",
    director: "Zika Liu",
    cinematographer: "Lu Xiqi",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/bmw-x5/bmw-x5-coverImg.jpg",
    span: 4,
    images: [
      "/nicola/bmw-x5/1.jpg",
      "/nicola/bmw-x5/2.jpg",
      "/nicola/bmw-x5/3.jpg",
      "/nicola/bmw-x5/4.jpg",
      "/nicola/bmw-x5/5.jpg",
      "/nicola/bmw-x5/6.jpg",
      "/nicola/bmw-x5/7.jpg",
      "/nicola/bmw-x5/8.jpg",
      "/nicola/bmw-x5/9.jpg",
      "/nicola/bmw-x5/10.jpg",
      "/nicola/bmw-x5/11.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "lollipop",
    video: "/project-videos/lollipop.mp4",
    name: "Lollipop",
    director: "Steven Ilous",
    cinematographer: "Tone Prot Promprot",
    productionCompany: "",
    category: "Film",
    cover: "/nicola/lollipop/lollipop-coverImg1.jpg",
    span: 2,
    images: [
      "/nicola/lollipop/1.jpg",
      "/nicola/lollipop/2.jpg",
      "/nicola/lollipop/3.jpg",
      "/nicola/lollipop/4.jpg",
      "/nicola/lollipop/5.jpg",
      "/nicola/lollipop/6.jpg",
      "/nicola/lollipop/7.jpg",
      "/nicola/lollipop/8.jpg",
      "/nicola/lollipop/9.jpg",
      "/nicola/lollipop/10.jpg",
      "/nicola/lollipop/11.jpg",
      "/nicola/lollipop/12.jpg",
      "/nicola/lollipop/13.jpg",
      "/nicola/lollipop/14.jpg",
      "/nicola/lollipop/15.jpg",
      "/nicola/lollipop/16.jpg",
      "/nicola/lollipop/17.jpg",
      "/nicola/lollipop/18.jpg",
      "/nicola/lollipop/19.jpg",
      "/nicola/lollipop/20.jpg",
      "/nicola/lollipop/21.jpg",
      "/nicola/lollipop/22.jpg",
      "/nicola/lollipop/23.jpg",
      "/nicola/lollipop/24.jpg",
      "/nicola/lollipop/25.jpg",
      "/nicola/lollipop/26.jpg",
      "/nicola/lollipop/27.jpg",
      "/nicola/lollipop/28.jpg",
      "/nicola/lollipop/29.jpg",
      "/nicola/lollipop/30.jpg",
      "/nicola/lollipop/31.jpg",
      "/nicola/lollipop/32.jpg",
      "/nicola/lollipop/33.jpg",
      "/nicola/lollipop/34.jpg",
      "/nicola/lollipop/35.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "crime-fiction",
    video: "/project-videos/crime-fiction.mp4",
    name: "Crime Fiction",
    director: "Dj",
    cinematographer: "Talin",
    productionCompany: "",
    category: "MV",
    cover: "/nicola/crime-fiction/crime-fiction-coverImg.JPG",
    span: 2,
    images: [
      "/nicola/crime-fiction/1.JPG",
      "/nicola/crime-fiction/2.JPG",
      "/nicola/crime-fiction/3.JPG",
      "/nicola/crime-fiction/4.JPG",
      "/nicola/crime-fiction/5.JPG",
      "/nicola/crime-fiction/6.JPG",
      "/nicola/crime-fiction/7.JPG",
      "/nicola/crime-fiction/8.JPG",
      "/nicola/crime-fiction/9.JPG",
      "/nicola/crime-fiction/10.JPG",
      "/nicola/crime-fiction/11.JPG",
      "/nicola/crime-fiction/12.JPG",
      "/nicola/crime-fiction/13.JPG",
      "/nicola/crime-fiction/14.JPG",
      "/nicola/crime-fiction/15.JPG",
      "/nicola/crime-fiction/16.JPG",
      "/nicola/crime-fiction/17.JPG",
      "/nicola/crime-fiction/18.JPG",
      "/nicola/crime-fiction/19.JPG",
      "/nicola/crime-fiction/20.JPG",
      "/nicola/crime-fiction/21.JPG",
      "/nicola/crime-fiction/22.JPG",
      "/nicola/crime-fiction/23.JPG",
      "/nicola/crime-fiction/24.JPG",
      "/nicola/crime-fiction/25.JPG",
      "/nicola/crime-fiction/26.JPG",
    ],
  },
  {
    artist: "nicola",
    id: "furla",
    video: "/project-videos/furla.mp4",
    name: "Furla",
    director: "Yuan",
    cinematographer: "Tetsuya Arimori",
    productionCompany: "kidzfrmnowhere.",
    category: "TVC",
    cover: "/nicola/furla/furla-coverImg.JPG",
    span: 4,
    images: [
      "/nicola/furla/1.JPG",
      "/nicola/furla/2.JPG",
      "/nicola/furla/3.JPG",
      "/nicola/furla/4.JPG",
      "/nicola/furla/5.JPG",
      "/nicola/furla/6.JPG",
      "/nicola/furla/7.JPG",
      "/nicola/furla/8.JPG",
      "/nicola/furla/9.JPG",
      "/nicola/furla/10.JPG",
      "/nicola/furla/11.jpg",
      "/nicola/furla/12.jpg",
      "/nicola/furla/13.jpg",
      "/nicola/furla/14.jpg",
      "/nicola/furla/15.jpg",
      "/nicola/furla/16.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "sony-ps5",
    video: "/project-videos/sony-ps5.mov",
    name: "Sony Ps5",
    director: "",
    cinematographer: "",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/sony-ps5/sony-ps5-coverImg.jpg",
    span: 4,
    images: [
      "/nicola/sony-ps5/1.jpg",
      "/nicola/sony-ps5/2.jpg",
      "/nicola/sony-ps5/3.jpg",
      "/nicola/sony-ps5/4.jpg",
      "/nicola/sony-ps5/5.jpg",
      "/nicola/sony-ps5/6.jpg",
      "/nicola/sony-ps5/7.jpg",
      "/nicola/sony-ps5/8.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "teva",
    video: "/project-videos/teva.mp4",
    name: "Teva",
    director: "Yuan",
    cinematographer: "Yuki Ono",
    productionCompany: "kidzfrmnowhere.",
    category: "TVC",
    cover: "/nicola/teva/teva-coverImg.jpg",
    span: 2,
    images: [
      "/nicola/teva/1.jpg",
      "/nicola/teva/2.jpg",
      "/nicola/teva/3.jpg",
      "/nicola/teva/4.jpg",
      "/nicola/teva/5.jpg",
      "/nicola/teva/6.jpg",
      "/nicola/teva/7.jpg",
      "/nicola/teva/8.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "beyond-symmetry",
    video: "/project-videos/beyond-symmetry.mp4",
    name: "Beyond Symmetry",
    director: "Amerigo Brini",
    cinematographer: "Stevo Shen",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/beyond-symmetry/beyond-symmetry-coverImg.jpg",
    span: 2,
    images: [
      "/nicola/beyond-symmetry/1.jpg",
      "/nicola/beyond-symmetry/2.jpg",
      "/nicola/beyond-symmetry/3.jpg",
      "/nicola/beyond-symmetry/4.jpg",
      "/nicola/beyond-symmetry/5.jpg",
      "/nicola/beyond-symmetry/6.jpg",
      "/nicola/beyond-symmetry/7.jpg",
      "/nicola/beyond-symmetry/8.jpg",
      "/nicola/beyond-symmetry/9.jpg",
      "/nicola/beyond-symmetry/10.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "revival-marni",
    video: "/project-videos/revival-marni.mp4",
    name: "Revival Marni",
    director: "Dwight Yao",
    cinematographer: "Yanqiu Fei",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/revival-marni/revival-marni-coverImg.jpg",
    span: 4,
    images: [
      "/nicola/revival-marni/1.jpg",
      "/nicola/revival-marni/2.jpg",
      "/nicola/revival-marni/3.jpg",
      "/nicola/revival-marni/4.jpg",
      "/nicola/revival-marni/5.jpg",
      "/nicola/revival-marni/6.jpg",
      "/nicola/revival-marni/7.jpg",
      "/nicola/revival-marni/8.jpg",
      "/nicola/revival-marni/9.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "amazon-prime",
    video: "/project-videos/amazon-prime.mp4",
    name: "Amazon Prime",
    director: "Vittorio Bonaffini",
    cinematographer: "Alessandro Ubaldi",
    productionCompany: "",
    category: "TVC",
    cover: "/nicola/amazon-prime/amazon-prime-coverImg.jpg",
    span: 4,
    images: [
      "/nicola/amazon-prime/1.jpg",
      "/nicola/amazon-prime/2.jpg",
      "/nicola/amazon-prime/3.jpg",
      "/nicola/amazon-prime/4.jpg",
      "/nicola/amazon-prime/5.jpg",
      "/nicola/amazon-prime/6.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "budweiser-be-a-king",
    video: "/project-videos/budweiser-be-a-king.mp4",
    name: "Budweiser Be a King",
    director: "Bharat Sikka",
    cinematographer: "",
    productionCompany: "Ransom Films",
    category: "TVC",
    cover: "/nicola/budweiser-be-a-king/budweiser-be-a-king-coverImg.jpg",
    span: 2,
    images: [
      "/nicola/budweiser-be-a-king/1.jpg",
      "/nicola/budweiser-be-a-king/2.jpg",
      "/nicola/budweiser-be-a-king/3.jpg",
      "/nicola/budweiser-be-a-king/4.jpg",
      "/nicola/budweiser-be-a-king/5.jpg",
      "/nicola/budweiser-be-a-king/6.jpg",
      "/nicola/budweiser-be-a-king/7.jpg",
      "/nicola/budweiser-be-a-king/8.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "to-the-moon",
    video: "/project-videos/to-the-moon.mp4",
    name: "To the Moon",
    director: "Weston Borg",
    cinematographer: "Jeremy Herron",
    productionCompany: "",
    category: "MV",
    cover: "/to-the-moon/to-the-moon-coverImg.jpg",
    cover: "/nicola/to-the-moon/1.jpg",
    // span: 2,
    images: [
      "/nicola/to-the-moon/1.jpg",
      "/nicola/to-the-moon/2.jpg",
      "/nicola/to-the-moon/3.jpg",
      "/nicola/to-the-moon/4.jpg",
      "/nicola/to-the-moon/5.jpg",
      "/nicola/to-the-moon/6.jpg",
      "/nicola/to-the-moon/7.jpg",
      "/nicola/to-the-moon/8.jpg",
      "/nicola/to-the-moon/9.jpg",
      "/nicola/to-the-moon/10.jpg",
      "/nicola/to-the-moon/11.jpg",
      "/nicola/to-the-moon/12.jpg",
      "/nicola/to-the-moon/13.jpg",
      "/nicola/to-the-moon/14.jpg",
      "/nicola/to-the-moon/15.jpg",
      "/nicola/to-the-moon/16.jpg",
      "/nicola/to-the-moon/17.jpg",
      "/nicola/to-the-moon/18.jpg",
      "/nicola/to-the-moon/19.jpg",
      "/nicola/to-the-moon/20.jpg",
      "/nicola/to-the-moon/21.jpg",
      "/nicola/to-the-moon/22.jpg",
      "/nicola/to-the-moon/23.jpg",
      "/nicola/to-the-moon/24.jpg",
      "/nicola/to-the-moon/25.jpg",
      "/nicola/to-the-moon/26.jpg",
      "/nicola/to-the-moon/27.jpg",
      "/nicola/to-the-moon/28.jpg",
      "/nicola/to-the-moon/29.jpg",
      "/nicola/to-the-moon/30.jpg",
      "/nicola/to-the-moon/31.jpg",
      "/nicola/to-the-moon/32.jpg",
      "/nicola/to-the-moon/33.jpg",
      "/nicola/to-the-moon/34.jpg",
      "/nicola/to-the-moon/35.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "bgmi",
    video: "/project-videos/bgmi.mp4",
    name: "BGMI",
    director: "Shai",
    cinematographer: "Yash Khanna",
    productionCompany: "Enter Jungle",
    category: "TVC",
    cover: "/nicola/bgmi/1.jpg",
    images: [
      "/nicola/bgmi/1.jpg",
      "/nicola/bgmi/2.jpg",
      "/nicola/bgmi/3.jpg",
      "/nicola/bgmi/4.jpg",
      "/nicola/bgmi/5.jpg",
      "/nicola/bgmi/6.jpg",
      "/nicola/bgmi/7.jpg",
      "/nicola/bgmi/8.jpg",
      "/nicola/bgmi/9.jpg",
      "/nicola/bgmi/10.jpg",
      "/nicola/bgmi/11.jpg",
      "/nicola/bgmi/12.jpg",
      "/nicola/bgmi/13.jpg",
      "/nicola/bgmi/14.jpg",
      "/nicola/bgmi/15.jpg",
      "/nicola/bgmi/16.jpg",
      "/nicola/bgmi/17.jpg",
      "/nicola/bgmi/18.jpg",
      "/nicola/bgmi/19.jpg",
      "/nicola/bgmi/20.jpg",
      "/nicola/bgmi/21.jpg",
      "/nicola/bgmi/22.jpg",
      "/nicola/bgmi/23.jpg",
      "/nicola/bgmi/24.jpg",
      "/nicola/bgmi/25.jpg",
      "/nicola/bgmi/26.jpg",
      "/nicola/bgmi/27.jpg",
      "/nicola/bgmi/28.jpg",
      "/nicola/bgmi/29.jpg",
      "/nicola/bgmi/30.jpg",
      "/nicola/bgmi/31.jpg",
      "/nicola/bgmi/32.jpg",
      "/nicola/bgmi/33.jpg",
      "/nicola/bgmi/34.jpg",
      "/nicola/bgmi/35.jpg",
      "/nicola/bgmi/36.jpg",
      "/nicola/bgmi/37.jpg",
      "/nicola/bgmi/38.jpg",
      "/nicola/bgmi/39.jpg",
      "/nicola/bgmi/40.jpg",
      "/nicola/bgmi/41.jpg",
      "/nicola/bgmi/42.jpg",
      "/nicola/bgmi/43.jpg",
    ],
  },
  {
    artist: "nicola",
    id: "gravity-lastlings",
    video: "/project-videos/gravity-lastlings.mp4",
    name: "Gravity Lastlings",
    director: "Rico Zhang",
    cinematographer: "Kenny Liu",
    productionCompany: "",
    category: "MV",
    cover: "/nicola/gravity-lastlings/gravity-lastlings-coverImg1.jpg",
    span: 4,
    images: [
      "/nicola/gravity-lastlings/1.jpg",
      "/nicola/gravity-lastlings/2.jpg",
      "/nicola/gravity-lastlings/3.jpg",
      "/nicola/gravity-lastlings/4.jpg",
      "/nicola/gravity-lastlings/5.jpg",
      "/nicola/gravity-lastlings/6.jpg",
      "/nicola/gravity-lastlings/7.jpg",
      "/nicola/gravity-lastlings/8.jpg",
      "/nicola/gravity-lastlings/9.jpg",
      "/nicola/gravity-lastlings/10.jpg",
      "/nicola/gravity-lastlings/11.jpg",
      "/nicola/gravity-lastlings/12.jpg",
      "/nicola/gravity-lastlings/13.jpg",
      "/nicola/gravity-lastlings/14.jpg",
      "/nicola/gravity-lastlings/15.jpg",
      "/nicola/gravity-lastlings/16.jpg",
      "/nicola/gravity-lastlings/17.jpg",
      "/nicola/gravity-lastlings/18.jpg",
      "/nicola/gravity-lastlings/19.jpg",
      "/nicola/gravity-lastlings/20.jpg",
      "/nicola/gravity-lastlings/21.jpg",
      "/nicola/gravity-lastlings/22.jpg",
      "/nicola/gravity-lastlings/23.jpg",
      "/nicola/gravity-lastlings/24.jpg",
      "/nicola/gravity-lastlings/25.jpg",
      "/nicola/gravity-lastlings/26.jpg",
      "/nicola/gravity-lastlings/27.jpg",
      "/nicola/gravity-lastlings/28.jpg",
      "/nicola/gravity-lastlings/29.jpg",
    ],
  },

  // missing assets

  // {
  //   id: "royal-stag",
  //   name: "Royal Stag",
  //   director: "Bharat Sikka",
  //   cinematographer: "Christopher Aoun",
  //   productionCompany: "Ransom Films",
  //   category: "TVC",
  //   cover: "/royal-stag/1.jpg",
  //   images: [
  //     "/royal-stag/1.jpg",
  //     "/royal-stag/2.jpg",
  //     "/royal-stag/3.jpg",
  //     "/royal-stag/4.jpg",
  //     "/royal-stag/5.jpg",
  //     "/royal-stag/6.jpg",
  //     "/royal-stag/7.jpg",
  //     "/royal-stag/8.jpg",
  //     "/royal-stag/9.jpg",
  //     "/royal-stag/10.jpg",
  //     "/royal-stag/11.jpg",
  //   ],
  // },
];

export const projects_agua = [
  {
    artist: "agua",
    id: "mengniu",
    video: "/project-videos/mengniu.mp4",
    name: "Mengniu",
    director: "Shen Yujie",
    cinematographer: "Jian Liwei",
    productionCompany: "Start Films",
    category: "Commercial",
    cover: "/agua/mengniu/mengniu-coverImg.jpg",
    images: [
      "/agua/mengniu/1.jpg",
      "/agua/mengniu/2.jpg",
      "/agua/mengniu/3.jpg",
      "/agua/mengniu/4.jpg",
      "/agua/mengniu/5.jpg",
      "/agua/mengniu/6.jpg",
      "/agua/mengniu/7.jpg",
      "/agua/mengniu/8.jpg",
      "/agua/mengniu/9.jpg",
      "/agua/mengniu/10.jpg",
      "/agua/mengniu/11.jpg",
      "/agua/mengniu/12.jpg",
      "/agua/mengniu/13.jpg",
      "/agua/mengniu/14.jpg",
      "/agua/mengniu/15.jpg",
      "/agua/mengniu/16.jpg",
      "/agua/mengniu/17.jpg",
    ],
  },
  {
    artist: "agua",
    id: "burberry-perfume",
    video: "/project-videos/burberry-perfume.mp4",
    name: "Burberry Perfume",
    director: "Zika Liu",
    cinematographer: "Lǎo Dòng",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/burberry-perfume/burberry-perfume-coverImg.jpg",
    images: [
      "/agua/burberry-perfume/1.jpg",
      "/agua/burberry-perfume/2.jpg",
      "/agua/burberry-perfume/3.jpg",
      "/agua/burberry-perfume/4.jpg",
      "/agua/burberry-perfume/5.jpg",
      "/agua/burberry-perfume/6.jpg",
      "/agua/burberry-perfume/7.jpg",
    ],
  },
  {
    artist: "agua",
    id: "shiseido",
    video: "/project-videos/shiseido.mp4",
    name: "Shiseido",
    director: "Dai Shu",
    cinematographer: "An Zheng",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/shiseido/shiseido-coverImg.jpg",
    images: [
      "/agua/shiseido/1.jpg",
      "/agua/shiseido/2.jpg",
      "/agua/shiseido/3.jpg",
      "/agua/shiseido/4.jpg",
      "/agua/shiseido/5.jpg",
    ],
  },
  {
    artist: "agua",
    id: "yili-cny",
    video: "/project-videos/yili-cny.mp4",
    name: "Yili CNY",
    director: "Wu Ershan, JB",
    cinematographer: "",
    productionCompany: "",
    category: "Film/TV",
    cover: "/agua/yili-cny/yili-cny-coverImg.jpg",
    images: [
      "/agua/yili-cny/1.jpg",
      "/agua/yili-cny/2.jpg",
      "/agua/yili-cny/3.jpg",
      "/agua/yili-cny/4.jpg",
      "/agua/yili-cny/5.jpg",
      "/agua/yili-cny/6.jpg",
      "/agua/yili-cny/7.jpg",
      "/agua/yili-cny/8.jpg",
      "/agua/yili-cny/9.jpg",
      "/agua/yili-cny/10.jpg",
    ],
  },
  {
    artist: "agua",
    id: "vili-n-jana",
    video: "/project-videos/vili-n-jana.mp4",
    name: "Vili n Jana",
    director: "Ding Yuchen",
    cinematographer: "Wang Tianxing",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/vili-n-jana/vili-n-jana-coverImg.jpg",
    images: [
      "/agua/vili-n-jana/1.jpg",
      "/agua/vili-n-jana/2.jpg",
      "/agua/vili-n-jana/3.jpg",
      "/agua/vili-n-jana/4.jpg",
      "/agua/vili-n-jana/5.jpg",
      "/agua/vili-n-jana/6.jpg",
      "/agua/vili-n-jana/7.jpg",
      "/agua/vili-n-jana/8.jpg",
      "/agua/vili-n-jana/9.jpg",
      "/agua/vili-n-jana/10.jpg",
    ],
  },
  {
    artist: "agua",
    id: "huawei-s9",
    video: "/project-videos/huawei-s9.mp4",
    name: "Huawei S9",
    director: "Jean Claude Thibaut",
    cinematographer: "Dariusz Wolski",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/huawei-s9/huawei-s9-coverImg.jpg",
    images: [
      "/agua/huawei-s9/1.jpg",
      "/agua/huawei-s9/2.jpg",
      "/agua/huawei-s9/3.jpg",
      "/agua/huawei-s9/4.jpg",
      "/agua/huawei-s9/5.jpg",
      "/agua/huawei-s9/6.jpg",
      "/agua/huawei-s9/7.jpg",
      "/agua/huawei-s9/8.jpg",
      "/agua/huawei-s9/9.jpg",
      "/agua/huawei-s9/10.jpg",
      "/agua/huawei-s9/11.jpg",
      "/agua/huawei-s9/12.jpg",
      "/agua/huawei-s9/13.jpg",
      "/agua/huawei-s9/14.jpg",
      "/agua/huawei-s9/15.jpg",
    ],
  },
  {
    artist: "agua",
    id: "earth-revival",
    video: "/project-videos/earth-revival.mp4",
    name: "Earth Revival",
    director: "Morten Vinther",
    cinematographer: "",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/earth-revival/earth-revival-coverImg.jpg",
    images: [
      "/agua/earth-revival/1.jpg",
      "/agua/earth-revival/2.jpg",
      "/agua/earth-revival/3.jpg",
      "/agua/earth-revival/4.jpg",
      "/agua/earth-revival/5.jpg",
      "/agua/earth-revival/6.jpg",
      "/agua/earth-revival/7.jpg",
    ],
  },
  {
    artist: "agua",
    id: "peacebird",
    video: "/project-videos/peacebird.mp4",
    name: "Peacebird",
    director: "Zika Liu",
    cinematographer: "An Zheng",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/peacebird/peacebird-coverImg1.jpg",
    images: [
      "/agua/peacebird/1.jpg",
      "/agua/peacebird/2.jpg",
      "/agua/peacebird/3.jpg",
      "/agua/peacebird/4.jpg",
      "/agua/peacebird/5.jpg",
      "/agua/peacebird/6.jpg",
      "/agua/peacebird/7.jpg",
      "/agua/peacebird/8.jpg",
      "/agua/peacebird/9.jpg",
      "/agua/peacebird/10.jpg",
    ],
  },
  {
    artist: "agua",
    id: "lululemon-cny",
    video: "/project-videos/lululemon-cny.mp4",
    name: "Lululemon CNY",
    director: "Fan Qing",
    cinematographer: "Lǎo Dòng",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/lululemon-cny/lululemon-cny-coverImg.jpg",
    images: [
      "/agua/lululemon-cny/1.jpg",
      "/agua/lululemon-cny/2.jpg",
      "/agua/lululemon-cny/3.jpg",
      "/agua/lululemon-cny/4.jpg",
      "/agua/lululemon-cny/5.jpg",
      "/agua/lululemon-cny/6.jpg",
      "/agua/lululemon-cny/7.jpg",
      "/agua/lululemon-cny/8.jpg",
      "/agua/lululemon-cny/9.jpg",
      "/agua/lululemon-cny/10.jpg",
      "/agua/lululemon-cny/11.jpg",
    ],
  },
  {
    artist: "agua",
    id: "zeekr-three-years",
    video: "/project-videos/zeekr-three-years.mp4",
    name: "Zeekr Three Years",
    director: "Will Wang",
    cinematographer: "Yuan Qiming",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/zeekr-three-years/zeekr-three-years-coverImg.jpg",
    images: [
      "/agua/zeekr-three-years/1.jpg",
      "/agua/zeekr-three-years/2.jpg",
      "/agua/zeekr-three-years/3.jpg",
      "/agua/zeekr-three-years/4.jpg",
      "/agua/zeekr-three-years/5.jpg",
      "/agua/zeekr-three-years/6.jpg",
      "/agua/zeekr-three-years/7.jpg",
      "/agua/zeekr-three-years/8.jpg",
      "/agua/zeekr-three-years/9.jpg",
      "/agua/zeekr-three-years/10.jpg",
      "/agua/zeekr-three-years/11.jpg",
      "/agua/zeekr-three-years/12.jpg",
      "/agua/zeekr-three-years/13.jpg",
      "/agua/zeekr-three-years/14.jpg",
    ],
  },
  {
    artist: "agua",
    id: "li-auto-i8",
    video: "/project-videos/li-auto-i8.mp4",
    name: "Li Auto I8",
    director: "Wei Ning",
    cinematographer: "Liang Zi",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/li-auto-i8/li-auto-i8-coverImg.jpg",
    images: [
      "/agua/li-auto-i8/1.jpg",
      "/agua/li-auto-i8/2.jpg",
      "/agua/li-auto-i8/3.jpg",
      "/agua/li-auto-i8/4.jpg",
      "/agua/li-auto-i8/5.jpg",
      "/agua/li-auto-i8/6.jpg",
      "/agua/li-auto-i8/7.jpg",
      "/agua/li-auto-i8/8.jpg",
      "/agua/li-auto-i8/9.jpg",
      "/agua/li-auto-i8/10.jpg",
      "/agua/li-auto-i8/11.jpg",
      "/agua/li-auto-i8/12.jpg",
      "/agua/li-auto-i8/13.jpg",
      "/agua/li-auto-i8/14.jpg",
      "/agua/li-auto-i8/15.jpg",
    ],
  },
  {
    artist: "agua",
    id: "audi-cny",
    video: "/project-videos/audi-cny.mp4",
    name: "Audi CNY",
    director: "Will Wang",
    cinematographer: "Ren Guangli",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/audi-cny/audi-cny-coverImg.jpg",
    images: [
      "/agua/audi-cny/1.jpg",
      "/agua/audi-cny/2.jpg",
      "/agua/audi-cny/3.jpg",
      "/agua/audi-cny/4.jpg",
      "/agua/audi-cny/5.jpg",
      "/agua/audi-cny/6.jpg",
      "/agua/audi-cny/7.jpg",
      "/agua/audi-cny/8.jpg",
      "/agua/audi-cny/9.jpg",
      "/agua/audi-cny/10.jpg",
    ],
  },
  {
    artist: "agua",
    id: "china-mobile",
    video: "/project-videos/china-mobile.mp4",
    name: "China Mobile",
    director: "Xu Wangliang",
    cinematographer: "Zhao Xuhui",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/china-mobile/china-mobile-coverImg.jpg",
    images: [
      "/agua/china-mobile/1.jpg",
      "/agua/china-mobile/2.jpg",
      "/agua/china-mobile/3.jpg",
      "/agua/china-mobile/4.jpg",
      "/agua/china-mobile/5.jpg",
      "/agua/china-mobile/6.jpg",
      "/agua/china-mobile/7.jpg",
      "/agua/china-mobile/8.jpg",
      "/agua/china-mobile/9.jpg",
      "/agua/china-mobile/10.jpg",
      "/agua/china-mobile/11.jpg",
      "/agua/china-mobile/12.jpg",
      "/agua/china-mobile/13.jpg",
    ],
  },
  {
    artist: "agua",
    id: "audi-rsgt",
    video: "/project-videos/audi-rsgt.mp4",
    name: "Audi RsGt",
    director: "Wei Ning",
    cinematographer: "Liangzi, Dufu",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/audi-rsgt/audi-rsgt-coverImg.jpg",
    images: [
      "/agua/audi-rsgt/1.jpg",
      "/agua/audi-rsgt/2.jpg",
      "/agua/audi-rsgt/3.jpg",
      "/agua/audi-rsgt/4.jpg",
      "/agua/audi-rsgt/5.jpg",
      "/agua/audi-rsgt/6.jpg",
      "/agua/audi-rsgt/7.jpg",
      "/agua/audi-rsgt/8.jpg",
    ],
  },
  {
    artist: "agua",
    id: "oppo-reno",
    video: "/project-videos/oppo-reno.mp4",
    name: "Oppo Reno",
    director: "Vincent Sylvain",
    cinematographer: "Nico Schrenk",
    productionCompany: "Radical Media",
    category: "Commercial",
    cover: "/agua/oppo-reno/oppo-reno-coverImg.jpg",
    images: [
      "/agua/oppo-reno/1.jpg",
      "/agua/oppo-reno/2.jpg",
      "/agua/oppo-reno/3.jpg",
      "/agua/oppo-reno/4.jpg",
      "/agua/oppo-reno/5.jpg",
      "/agua/oppo-reno/6.jpg",
      "/agua/oppo-reno/7.jpg",
      "/agua/oppo-reno/8.jpg",
      "/agua/oppo-reno/9.jpg",
      "/agua/oppo-reno/10.jpg",
      "/agua/oppo-reno/11.jpg",
    ],
  },
  {
    artist: "agua",
    id: "lululemon",
    video: "/project-videos/lululemon.mp4",
    name: "Lululemon",
    director: "Colin Solal Cardo",
    cinematographer: "Madison McKamey",
    productionCompany: "Stink Films",
    category: "Commercial",
    cover: "/agua/lululemon/lululemon-coverImg.jpg",
    images: [
      "/agua/lululemon/1.jpg",
      "/agua/lululemon/2.jpg",
      "/agua/lululemon/3.jpg",
      "/agua/lululemon/4.jpg",
      "/agua/lululemon/5.jpg",
      "/agua/lululemon/6.jpg",
      "/agua/lululemon/7.jpg",
      "/agua/lululemon/8.jpg",
      "/agua/lululemon/9.jpg",
      "/agua/lululemon/10.jpg",
      "/agua/lululemon/11.jpg",
    ],
  },
  {
    artist: "agua",
    id: "redmi-n13",
    video: "/project-videos/redmi-n13.mp4",
    name: "Redmi N13",
    director: "Wu Ting",
    cinematographer: "Dustin",
    productionCompany: "Vision Hill Road",
    category: "Commercial",
    cover: "/agua/redmi-n13/redmi-n13-coverImg.jpg",
    images: [
      "/agua/redmi-n13/1.jpg",
      "/agua/redmi-n13/2.jpg",
      "/agua/redmi-n13/3.jpg",
      "/agua/redmi-n13/4.jpg",
      "/agua/redmi-n13/5.jpg",
      "/agua/redmi-n13/6.jpg",
      "/agua/redmi-n13/7.jpg",
      "/agua/redmi-n13/8.jpg",
      "/agua/redmi-n13/9.jpg",
      "/agua/redmi-n13/10.jpg",
    ],
  },
  {
    artist: "agua",
    id: "neiwai-active",
    video: "/project-videos/neiwai-active.mp4",
    name: "Neiwai Active",
    director: "Fan Qing",
    cinematographer: "Lǎo Dòng",
    productionCompany: "",
    category: "Commercial",
    cover: "/agua/neiwai-active/neiwai-active-coverImg.jpg",
    images: [
      "/agua/neiwai-active/1.jpg",
      "/agua/neiwai-active/2.jpg",
      "/agua/neiwai-active/3.jpg",
      "/agua/neiwai-active/4.jpg",
      "/agua/neiwai-active/5.jpg",
      "/agua/neiwai-active/6.jpg",
      "/agua/neiwai-active/7.jpg",
      "/agua/neiwai-active/8.jpg",
      "/agua/neiwai-active/9.jpg",
    ],
  },
];

export function getAllProjects() {
  const result = [];
  const maxLength = Math.max(projects_nicola.length, projects_agua.length);

  for (let i = 0; i < maxLength; i++) {
    if (projects_nicola[i]) {
      const { span, ...rest } = projects_nicola[i];
      result.push({ ...rest, author: "nicola" });
    }
    if (projects_agua[i]) {
      result.push({ ...projects_agua[i], author: "agua" });
    }
  }

  return result;
}

export const projects = getAllProjects();
