export const projects = [
  {
    id: "apple-security",
    name: "Apple Security",
    director: "Adam Liu",
    cinematographer: "TianXing Wang",
    productionCompany: "",
    category: "TVC",
    cover: "/apple-security/1.jpg",
    span: 4,
    images: [
      "/apple-security/1.jpg",
      "/apple-security/2.jpg",
      "/apple-security/3.jpg",
      "/apple-security/4.jpg",
      "/apple-security/5.jpg",
      "/apple-security/6.jpg",
      "/apple-security/7.jpg",
      "/apple-security/8.jpg",
    ],
  },
  {
    id: "neeraj",
    name: "Neeraj",
    director: "Aakash Bhatia",
    cinematographer: "Konrad Losch",
    productionCompany: "Loudmouth",
    category: "TVC",
    cover: "/neeraj/1.JPG",
    span: 2,
    images: [
      "/neeraj/1.JPG",
      "/neeraj/2.jpg",
      "/neeraj/3.jpg",
      "/neeraj/4.jpg",
      "/neeraj/5.jpg",
      "/neeraj/6.jpg",
      "/neeraj/7.jpg",
      "/neeraj/8.jpg",
      "/neeraj/9.jpg",
      "/neeraj/10.jpg",
      "/neeraj/11.jpg",
      "/neeraj/12.jpg",
      "/neeraj/13.jpg",
      "/neeraj/14.jpg",
      "/neeraj/15.jpg",
      "/neeraj/16.jpg",
      "/neeraj/17.jpg",
      "/neeraj/18.jpg",
      "/neeraj/19.jpg",
      "/neeraj/20.jpg",
      "/neeraj/21.jpg",
      "/neeraj/22.jpg",
    ],
  },
  {
    id: "astropulse",
    name: "Astropulse",
    director: "Wei Wang",
    cinematographer: "",
    productionCompany: "",
    category: "TVC",
    cover: "/astropulse/1.jpg",
    span: 2,
    images: [
      "/astropulse/1.jpg",
      "/astropulse/2.jpg",
      "/astropulse/3.jpg",
      "/astropulse/4.jpg",
      "/astropulse/5.jpg",
      "/astropulse/6.jpg",
      "/astropulse/7.jpg",
    ],
  },
  {
    id: "lotus-limitless",
    name: "Lotus Limitless",
    director: "Yao Fei",
    cinematographer: "Lu Xiqi",
    productionCompany: "",
    category: "TVC",
    cover: "/lotus-limitless/1.jpg",
    span: 4,
    images: [
      "/lotus-limitless/1.jpg",
      "/lotus-limitless/2.jpg",
      "/lotus-limitless/3.jpg",
      "/lotus-limitless/4.jpg",
      "/lotus-limitless/5.jpg",
      "/lotus-limitless/6.jpg",
      "/lotus-limitless/7.jpg",
      "/lotus-limitless/8.jpg",
      "/lotus-limitless/9.jpg",
      "/lotus-limitless/10.jpg",
      "/lotus-limitless/11.jpg",
      "/lotus-limitless/12.jpg",
      "/lotus-limitless/13.jpg",
      "/lotus-limitless/14.jpg",
      "/lotus-limitless/15.jpg",
      "/lotus-limitless/16.jpg",
      "/lotus-limitless/17.jpg",
      "/lotus-limitless/18.jpg",
      "/lotus-limitless/19.jpg",
      "/lotus-limitless/20.jpg",
      "/lotus-limitless/21.jpg",
      "/lotus-limitless/22.jpg",
      "/lotus-limitless/23.jpg",
      "/lotus-limitless/24.jpg",
      "/lotus-limitless/25.jpg",
      "/lotus-limitless/26.jpg",
      "/lotus-limitless/27.jpg",
      "/lotus-limitless/28.jpg",
      "/lotus-limitless/29.jpg",
      "/lotus-limitless/30.jpg",
      "/lotus-limitless/31.jpg",
      "/lotus-limitless/32.jpg",
      "/lotus-limitless/33.jpg",
      "/lotus-limitless/34.jpg",
      "/lotus-limitless/35.jpg",
      "/lotus-limitless/36.jpg",
    ],
  },
  {
    id: "honkai-star-trail",
    name: "Honkai Star Trail",
    director: "Omer Ben Shachar",
    cinematographer: "Kai Krause",
    productionCompany: "",
    category: "Film",
    cover: "/honkai-star-trail/1.jpg",
    span: 4,
    images: [
      "/honkai-star-trail/1.jpg",
      "/honkai-star-trail/2.jpg",
      "/honkai-star-trail/3.jpg",
      "/honkai-star-trail/4.jpg",
      "/honkai-star-trail/5.jpg",
      "/honkai-star-trail/6.jpg",
      "/honkai-star-trail/7.jpg",
      "/honkai-star-trail/8.jpg",
      "/honkai-star-trail/9.jpg",
      "/honkai-star-trail/10.jpg",
    ],
  },
  {
    id: "blossom-shanghai",
    name: "Blossom Shanghai",
    director: "Wong Kar-wai",
    cinematographer: "Peter Pau",
    productionCompany: "",
    category: "Film",
    cover: "/blossom-shanghai/1.jpg",
    span: 2,
    images: [
      "/blossom-shanghai/1.jpg",
      "/blossom-shanghai/2.jpg",
      "/blossom-shanghai/3.jpg",
      "/blossom-shanghai/4.jpg",
      "/blossom-shanghai/5.jpg",
      "/blossom-shanghai/6.jpg",
      "/blossom-shanghai/7.jpg",
      "/blossom-shanghai/8.jpg",
      "/blossom-shanghai/9.jpg",
    ],
  },
  {
    id: "beats",
    name: "Beats",
    director: "Zika Liu",
    cinematographer: "Liu Chao",
    productionCompany: "",
    category: "TVC",
    cover: "/beats/1.jpg",
    span: 2,
    images: [
      "/beats/1.jpg",
      "/beats/2.jpg",
      "/beats/3.jpg",
      "/beats/4.jpg",
      "/beats/5.jpg",
      "/beats/6.jpg",
      "/beats/7.jpg",
      "/beats/8.jpg",
    ],
  },
  {
    id: "royal-enfield",
    name: "Royal Enfield",
    director: "Aakash Bhatia",
    cinematographer: "Vikash Nowlakha",
    productionCompany: "Loudmouth",
    category: "TVC",
    cover: "/royal-enfield/1.jpg",
    span: 4,
    images: [
      "/royal-enfield/1.jpg",
      "/royal-enfield/2.jpg",
      "/royal-enfield/3.jpg",
      "/royal-enfield/4.jpg",
      "/royal-enfield/5.jpg",
    ],
  },
  {
    id: "bmw-x5",
    name: "Bmw X5",
    director: "Zika Liu",
    cinematographer: "Lu Xiqi",
    productionCompany: "",
    category: "TVC",
    cover: "/bmw-x5/1.jpg",
    span: 4,
    images: [
      "/bmw-x5/1.jpg",
      "/bmw-x5/2.jpg",
      "/bmw-x5/3.jpg",
      "/bmw-x5/4.jpg",
      "/bmw-x5/5.jpg",
      "/bmw-x5/6.jpg",
      "/bmw-x5/7.jpg",
      "/bmw-x5/8.jpg",
      "/bmw-x5/9.jpg",
      "/bmw-x5/10.jpg",
      "/bmw-x5/11.jpg",
    ],
  },
  {
    id: "lollipop",
    name: "Lollipop",
    director: "Steven Ilous",
    cinematographer: "Tone Prot Promprot",
    productionCompany: "",
    category: "Film",
    cover: "/lollipop/1.jpg",
    span: 2,
    images: [
      "/lollipop/1.jpg",
      "/lollipop/2.jpg",
      "/lollipop/3.jpg",
      "/lollipop/4.jpg",
      "/lollipop/5.jpg",
      "/lollipop/6.jpg",
      "/lollipop/7.jpg",
      "/lollipop/8.jpg",
      "/lollipop/9.jpg",
      "/lollipop/10.jpg",
      "/lollipop/11.jpg",
      "/lollipop/12.jpg",
      "/lollipop/13.jpg",
      "/lollipop/14.jpg",
      "/lollipop/15.jpg",
      "/lollipop/16.jpg",
      "/lollipop/17.jpg",
      "/lollipop/18.jpg",
      "/lollipop/19.jpg",
      "/lollipop/20.jpg",
      "/lollipop/21.jpg",
      "/lollipop/22.jpg",
      "/lollipop/23.jpg",
      "/lollipop/24.jpg",
      "/lollipop/25.jpg",
      "/lollipop/26.jpg",
      "/lollipop/27.jpg",
      "/lollipop/28.jpg",
      "/lollipop/29.jpg",
      "/lollipop/30.jpg",
      "/lollipop/31.jpg",
      "/lollipop/32.jpg",
      "/lollipop/33.jpg",
      "/lollipop/34.jpg",
      "/lollipop/35.jpg",
    ],
  },
  {
    id: "crime-fiction",
    name: "Crime Fiction",
    director: "Dj",
    cinematographer: "Talin",
    productionCompany: "",
    category: "MV",
    cover: "/crime-fiction/1.JPG",
    span: 2,
    images: [
      "/crime-fiction/1.JPG",
      "/crime-fiction/2.JPG",
      "/crime-fiction/3.JPG",
      "/crime-fiction/4.JPG",
      "/crime-fiction/5.JPG",
      "/crime-fiction/6.JPG",
      "/crime-fiction/7.JPG",
      "/crime-fiction/8.JPG",
      "/crime-fiction/9.JPG",
      "/crime-fiction/10.JPG",
      "/crime-fiction/11.JPG",
      "/crime-fiction/12.JPG",
      "/crime-fiction/13.JPG",
      "/crime-fiction/14.JPG",
      "/crime-fiction/15.JPG",
      "/crime-fiction/16.JPG",
      "/crime-fiction/17.JPG",
      "/crime-fiction/18.JPG",
      "/crime-fiction/19.JPG",
      "/crime-fiction/20.JPG",
      "/crime-fiction/21.JPG",
      "/crime-fiction/22.JPG",
      "/crime-fiction/23.JPG",
      "/crime-fiction/24.JPG",
      "/crime-fiction/25.JPG",
      "/crime-fiction/26.JPG",
    ],
  },
  {
    id: "furla",
    name: "Furla",
    director: "Yuan",
    cinematographer: "Tetsuya Arimori",
    productionCompany: "kidzfrmnowhere.",
    category: "TVC",
    cover: "/furla/1.JPG",
    span: 4,
    images: [
      "/furla/1.JPG",
      "/furla/2.JPG",
      "/furla/3.JPG",
      "/furla/4.JPG",
      "/furla/5.JPG",
      "/furla/6.JPG",
      "/furla/7.JPG",
      "/furla/8.JPG",
      "/furla/9.JPG",
      "/furla/10.JPG",
      "/furla/11.jpg",
      "/furla/12.jpg",
      "/furla/13.jpg",
      "/furla/14.jpg",
      "/furla/15.jpg",
      "/furla/16.jpg",
    ],
  },
  {
    id: "sony-ps5",
    name: "Sony Ps5",
    director: "",
    cinematographer: "",
    productionCompany: "",
    category: "TVC",
    cover: "/sony-ps5/1.jpg",
    span: 4,
    images: [
      "/sony-ps5/1.jpg",
      "/sony-ps5/2.jpg",
      "/sony-ps5/3.jpg",
      "/sony-ps5/4.jpg",
      "/sony-ps5/5.jpg",
      "/sony-ps5/6.jpg",
      "/sony-ps5/7.jpg",
      "/sony-ps5/8.jpg",
    ],
  },
  {
    id: "teva",
    name: "Teva",
    director: "Yuan",
    cinematographer: "Yuki Ono",
    productionCompany: "kidzfrmnowhere.",
    category: "TVC",
    cover: "/teva/1.jpg",
    span: 2,
    images: [
      "/teva/1.jpg",
      "/teva/2.jpg",
      "/teva/3.jpg",
      "/teva/4.jpg",
      "/teva/5.jpg",
      "/teva/6.jpg",
      "/teva/7.jpg",
      "/teva/8.jpg",
    ],
  },
  {
    id: "beyond-symmetry",
    name: "Beyond Symmetry",
    director: "Amerigo Brini",
    cinematographer: "Stevo Shen",
    productionCompany: "",
    category: "TVC",
    cover: "/beyond-symmetry/1.jpg",
    span: 2,
    images: [
      "/beyond-symmetry/1.jpg",
      "/beyond-symmetry/2.jpg",
      "/beyond-symmetry/3.jpg",
      "/beyond-symmetry/4.jpg",
      "/beyond-symmetry/5.jpg",
      "/beyond-symmetry/6.jpg",
      "/beyond-symmetry/7.jpg",
      "/beyond-symmetry/8.jpg",
      "/beyond-symmetry/9.jpg",
      "/beyond-symmetry/10.jpg",
    ],
  },
  {
    id: "revival-marni",
    name: "Revival Marni",
    director: "Dwight Yao",
    cinematographer: "Yanqiu Fei",
    productionCompany: "",
    category: "TVC",
    cover: "/revival-marni/1.jpg",
    span: 4,
    images: [
      "/revival-marni/1.jpg",
      "/revival-marni/2.jpg",
      "/revival-marni/3.jpg",
      "/revival-marni/4.jpg",
      "/revival-marni/5.jpg",
      "/revival-marni/6.jpg",
      "/revival-marni/7.jpg",
      "/revival-marni/8.jpg",
      "/revival-marni/9.jpg",
    ],
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime",
    director: "Vittorio Bonaffini",
    cinematographer: "Alessandro Ubaldi",
    productionCompany: "",
    category: "TVC",
    cover: "/amazon-prime/1.jpg",
    span: 4,
    images: [
      "/amazon-prime/1.jpg",
      "/amazon-prime/2.jpg",
      "/amazon-prime/3.jpg",
      "/amazon-prime/4.jpg",
      "/amazon-prime/5.jpg",
      "/amazon-prime/6.jpg",
    ],
  },
  {
    id: "budweiser-be-a-king",
    name: "Budweiser Be a King",
    director: "Bharat Sikka",
    cinematographer: "",
    productionCompany: "Ransom Films",
    category: "TVC",
    cover: "/budweiser-be-a-king/1.jpg",
    span: 2,
    images: [
      "/budweiser-be-a-king/1.jpg",
      "/budweiser-be-a-king/2.jpg",
      "/budweiser-be-a-king/3.jpg",
      "/budweiser-be-a-king/4.jpg",
      "/budweiser-be-a-king/5.jpg",
      "/budweiser-be-a-king/6.jpg",
      "/budweiser-be-a-king/7.jpg",
      "/budweiser-be-a-king/8.jpg",
    ],
  },

  // missing assets

  // {
  //   id: "royal-stag",
  //   name: "Royal Stag",
  //   director: "Bharat Sikka",
  //   cinematographer: "Christopher Aoun",
  //   productionCompany: "Ransom Films",
  //   category: "TVC",
  //   cover: "/royal-stag/1.jpg",
  //   images: [
  //     "/royal-stag/1.jpg",
  //     "/royal-stag/2.jpg",
  //     "/royal-stag/3.jpg",
  //     "/royal-stag/4.jpg",
  //     "/royal-stag/5.jpg",
  //     "/royal-stag/6.jpg",
  //     "/royal-stag/7.jpg",
  //     "/royal-stag/8.jpg",
  //     "/royal-stag/9.jpg",
  //     "/royal-stag/10.jpg",
  //     "/royal-stag/11.jpg",
  //   ],
  // },

  // {
  //   id: "gravity-laslingt",
  //   name: "Gravity Laslingt",
  //   director: "",
  //   cinematographer: "",
  //   productionCompany: "",
  //   category: "MV",
  // },

  // {
  //   id: "bgmi",
  //   name: "BGMI",
  //   director: "Shai",
  //   cinematographer: "Yash Khanna",
  //   productionCompany: "Enter Jungle",
  //   category: "TVC",
  //   cover: "/bgmi/1.jpg",
  //   images: [
  //     "/bgmi/1.jpg",
  //     "/bgmi/2.jpg",
  //     "/bgmi/3.jpg",
  //     "/bgmi/4.jpg",
  //     "/bgmi/5.jpg",
  //     "/bgmi/6.jpg",
  //     "/bgmi/7.jpg",
  //     "/bgmi/8.jpg",
  //     "/bgmi/9.jpg",
  //     "/bgmi/10.jpg",
  //     "/bgmi/11.jpg",
  //   ],
  // },
  //
];
